/**
 * Migration immutability. prisma/migration-manifest.json records every
 * migration directory under prisma/migrations with the SHA-256 of every file
 * in it (migration.sql's hash is exactly the checksum Prisma stores in
 * _prisma_migrations), plus migration_lock.toml and the accepted retired
 * history.
 *
 * CI (scripts/db/check-migration-manifest.ts) enforces:
 *  - the repository matches the manifest: nothing edited, renamed, deleted,
 *    added to or removed from a migration directory, and no migration added
 *    without its manifest entry (which puts it in front of a reviewer as a
 *    manifest diff);
 *  - against the base commit (the push's previous head, or a pull request's
 *    base): every migration that existed there is byte-for-byte unchanged,
 *    and the manifest only grew, at the end.
 * The production migration workflow adds the third comparison - the
 * database's recorded checksums against these same files - through
 * history.ts.
 *
 * Pure: no filesystem, git or database access. Self-contained relative
 * imports, because scripts/db/ runs it through tsx.
 */
import { MIGRATION_NAME, RETIRED_MIGRATIONS, type LocalMigration } from "./history";

export const MANIFEST_PATH = "prisma/migration-manifest.json";
export const MIGRATIONS_PATH = "prisma/migrations";
export const MANIFEST_VERSION = 1;

const SHA256 = /^[0-9a-f]{64}$/;

/** Every file in one migration directory, by path relative to it, with its SHA-256. */
export type MigrationDirectory = {
  name: string;
  files: Record<string, string>;
};

/** What prisma/migrations holds, from disk or from a git commit. */
export type MigrationsSnapshot = {
  /** SHA-256 of migration_lock.toml, or null if it's missing. */
  lockFile: string | null;
  /** Anything at the top level other than migration_lock.toml and directories. */
  strayEntries: string[];
  directories: MigrationDirectory[];
};

export type MigrationManifest = {
  version: typeof MANIFEST_VERSION;
  migrationLock: string;
  migrations: MigrationDirectory[];
  retired: LocalMigration[];
};

const MANIFEST_COMMENT =
  "Generated by `npm run db:manifest` - never edit by hand. CI fails if any migration listed here " +
  "is edited, renamed or deleted, or if prisma/migrations gains a migration without an entry. " +
  "See src/lib/migrationSafety/manifest.ts.";

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function timestampOf(name: string): string {
  return name.slice(0, 14);
}

function sameFiles(a: Record<string, string>, b: Record<string, string>): boolean {
  const aKeys = Object.keys(a).sort();
  const bKeys = Object.keys(b).sort();
  return aKeys.length === bKeys.length && aKeys.every((key, i) => key === bKeys[i] && a[key] === b[key]);
}

function sameRetired(a: readonly LocalMigration[], b: readonly LocalMigration[]): boolean {
  const key = (m: LocalMigration) => `${m.name}:${m.checksum}`;
  const aKeys = a.map(key).sort();
  const bKeys = b.map(key).sort();
  return aKeys.length === bKeys.length && aKeys.every((k, i) => k === bKeys[i]);
}

/** Validates the manifest's shape; returns null alongside the problems if it can't be trusted at all. */
export function parseManifest(value: unknown): { manifest: MigrationManifest | null; problems: string[] } {
  const problems: string[] = [];
  if (!isRecord(value)) return { manifest: null, problems: ["The manifest isn't a JSON object."] };
  if (value.version !== MANIFEST_VERSION) {
    return { manifest: null, problems: [`The manifest's version is ${JSON.stringify(value.version)}, expected ${MANIFEST_VERSION}.`] };
  }
  if (typeof value.migrationLock !== "string" || !SHA256.test(value.migrationLock)) {
    problems.push("The manifest's migrationLock isn't a SHA-256.");
  }
  if (!Array.isArray(value.migrations)) return { manifest: null, problems: [...problems, "The manifest has no migrations list."] };
  if (!Array.isArray(value.retired)) return { manifest: null, problems: [...problems, "The manifest has no retired list."] };

  const migrations: MigrationDirectory[] = [];
  value.migrations.forEach((entry, index) => {
    const where = `Manifest entry #${index + 1}`;
    if (!isRecord(entry) || typeof entry.name !== "string") {
      problems.push(`${where} has no name.`);
      return;
    }
    if (!MIGRATION_NAME.test(entry.name)) problems.push(`${where} ("${entry.name}") isn't named <14-digit timestamp>_<name>.`);
    if (!isRecord(entry.files) || Object.keys(entry.files).length === 0) {
      problems.push(`${where} ("${entry.name}") lists no files.`);
      return;
    }
    const files: Record<string, string> = {};
    for (const [file, hash] of Object.entries(entry.files)) {
      if (typeof hash !== "string" || !SHA256.test(hash)) {
        problems.push(`${where} ("${entry.name}") has a malformed hash for ${file}.`);
      } else {
        files[file] = hash;
      }
    }
    if (!("migration.sql" in entry.files)) problems.push(`${where} ("${entry.name}") doesn't list migration.sql.`);
    migrations.push({ name: entry.name, files });
  });

  for (let i = 1; i < migrations.length; i++) {
    const previous = migrations[i - 1].name;
    const current = migrations[i].name;
    if (current === previous) problems.push(`The manifest lists "${current}" twice.`);
    else if (current < previous) problems.push(`The manifest isn't in order: "${current}" comes after "${previous}".`);
    else if (timestampOf(current) === timestampOf(previous)) {
      problems.push(`"${previous}" and "${current}" share a timestamp, so their order is ambiguous.`);
    }
  }

  const retired: LocalMigration[] = [];
  value.retired.forEach((entry, index) => {
    if (!isRecord(entry) || typeof entry.name !== "string" || typeof entry.checksum !== "string" || !SHA256.test(entry.checksum)) {
      problems.push(`Retired entry #${index + 1} is malformed.`);
      return;
    }
    retired.push({ name: entry.name, checksum: entry.checksum });
  });

  return {
    manifest: {
      version: MANIFEST_VERSION,
      migrationLock: typeof value.migrationLock === "string" ? value.migrationLock : "",
      migrations,
      retired,
    },
    problems,
  };
}

/** The repository's prisma/migrations against the committed manifest. */
export function checkSnapshotAgainstManifest(
  snapshot: MigrationsSnapshot,
  manifest: MigrationManifest,
  retiredMigrations: readonly LocalMigration[] = RETIRED_MIGRATIONS,
): string[] {
  const problems: string[] = [];

  if (snapshot.lockFile === null) problems.push("prisma/migrations/migration_lock.toml is missing.");
  else if (snapshot.lockFile !== manifest.migrationLock) problems.push("prisma/migrations/migration_lock.toml changed.");
  for (const entry of snapshot.strayEntries) {
    problems.push(`prisma/migrations/${entry} isn't a migration directory or migration_lock.toml.`);
  }

  const onDisk = new Map(snapshot.directories.map((dir) => [dir.name, dir]));
  const inManifest = new Set(manifest.migrations.map((entry) => entry.name));

  for (const entry of manifest.migrations) {
    const dir = onDisk.get(entry.name);
    if (!dir) {
      problems.push(`Migration "${entry.name}" was deleted or renamed - it's in the manifest but not in prisma/migrations.`);
      continue;
    }
    for (const [file, hash] of Object.entries(entry.files)) {
      if (!(file in dir.files)) problems.push(`Migration "${entry.name}": ${file} was deleted.`);
      else if (dir.files[file] !== hash) problems.push(`Migration "${entry.name}": ${file} was edited.`);
    }
    for (const file of Object.keys(dir.files)) {
      if (!(file in entry.files)) problems.push(`Migration "${entry.name}": ${file} was added to an existing migration.`);
    }
  }

  const seenTimestamps = new Map<string, string>();
  for (const dir of snapshot.directories) {
    if (!MIGRATION_NAME.test(dir.name)) problems.push(`prisma/migrations/${dir.name} isn't named <14-digit timestamp>_<name>.`);
    if (!("migration.sql" in dir.files)) problems.push(`prisma/migrations/${dir.name} has no migration.sql.`);
    const clash = seenTimestamps.get(timestampOf(dir.name));
    if (clash) problems.push(`Migrations "${clash}" and "${dir.name}" share a timestamp, so their order is ambiguous.`);
    seenTimestamps.set(timestampOf(dir.name), dir.name);
    if (!inManifest.has(dir.name)) {
      problems.push(
        `Migration "${dir.name}" isn't in the manifest. If it's a genuinely new migration, run ` +
          `\`npm run db:manifest\` and commit the manifest with it.`,
      );
    }
  }

  // The retired history is fixed by history.ts; the manifest must agree exactly.
  if (!sameRetired(manifest.retired, retiredMigrations)) {
    problems.push("The manifest's retired list doesn't match RETIRED_MIGRATIONS in src/lib/migrationSafety/history.ts.");
  }
  for (const retired of retiredMigrations) {
    if (onDisk.has(retired.name) || inManifest.has(retired.name)) {
      problems.push(`"${retired.name}" is retired production history and must never reappear as a migration.`);
    }
  }

  return problems;
}

/** Everything that existed at the base commit must still exist, byte-for-byte; new migrations only after it. */
export function checkSnapshotAppendOnly(base: MigrationsSnapshot, current: MigrationsSnapshot): string[] {
  const problems: string[] = [];
  const currentByName = new Map(current.directories.map((dir) => [dir.name, dir]));

  if (base.lockFile !== null && base.lockFile !== current.lockFile) {
    problems.push("prisma/migrations/migration_lock.toml changed since the base commit.");
  }
  for (const dir of base.directories) {
    const now = currentByName.get(dir.name);
    if (!now) problems.push(`Migration "${dir.name}" existed at the base commit and was deleted or renamed.`);
    else if (!sameFiles(dir.files, now.files)) problems.push(`Migration "${dir.name}" was changed since the base commit.`);
  }

  const latestBase = base.directories.map((dir) => dir.name).sort().at(-1);
  if (latestBase) {
    const baseNames = new Set(base.directories.map((dir) => dir.name));
    for (const dir of current.directories) {
      if (!baseNames.has(dir.name) && dir.name < latestBase) {
        problems.push(`New migration "${dir.name}" is older than "${latestBase}", which already existed - give it a new timestamp.`);
      }
    }
  }
  return problems;
}

/** The manifest may only grow, at the end. Catches a migration edit "fixed" by regenerating the manifest. */
export function checkManifestAppendOnly(base: MigrationManifest, current: MigrationManifest): string[] {
  const problems: string[] = [];
  if (base.migrationLock !== current.migrationLock) problems.push("The manifest's migrationLock changed since the base commit.");
  if (!sameRetired(base.retired, current.retired)) problems.push("The manifest's retired list changed since the base commit.");
  base.migrations.forEach((entry, index) => {
    const now = current.migrations[index];
    if (!now || now.name !== entry.name || !sameFiles(entry.files, now.files)) {
      problems.push(`Manifest entry "${entry.name}" was changed, removed or reordered since the base commit.`);
    }
  });
  return problems;
}

/**
 * The manifest for `snapshot`: the previous manifest's entries, which must
 * still match exactly, plus any new migrations appended in order. Refuses
 * rather than rewriting history.
 */
export function buildManifest(
  snapshot: MigrationsSnapshot,
  previous: MigrationManifest | null,
  retiredMigrations: readonly LocalMigration[] = RETIRED_MIGRATIONS,
): { manifest: MigrationManifest | null; added: string[]; problems: string[] } {
  if (snapshot.lockFile === null) {
    return { manifest: null, added: [], problems: ["prisma/migrations/migration_lock.toml is missing."] };
  }
  const draft: MigrationManifest = {
    version: MANIFEST_VERSION,
    migrationLock: previous?.migrationLock ?? snapshot.lockFile,
    migrations: [...(previous?.migrations ?? [])],
    retired: [...retiredMigrations],
  };
  const known = new Set(draft.migrations.map((entry) => entry.name));
  const added = snapshot.directories
    .filter((dir) => !known.has(dir.name))
    .map((dir) => dir.name)
    .sort();
  for (const name of added) {
    const dir = snapshot.directories.find((d) => d.name === name);
    if (dir) draft.migrations.push({ name: dir.name, files: { ...dir.files } });
  }

  const problems = checkSnapshotAgainstManifest(snapshot, draft, retiredMigrations);
  if (previous) {
    const latestPrevious = previous.migrations.at(-1)?.name;
    for (const name of added) {
      if (latestPrevious && name < latestPrevious) {
        problems.push(`New migration "${name}" is older than "${latestPrevious}" - give it a new timestamp.`);
      }
    }
  }
  return problems.length > 0 ? { manifest: null, added, problems } : { manifest: draft, added, problems: [] };
}

/** Stable output: fixed key order, files sorted, two-space indent, trailing newline. */
export function serializeManifest(manifest: MigrationManifest): string {
  const ordered = {
    _comment: MANIFEST_COMMENT,
    version: manifest.version,
    migrationLock: manifest.migrationLock,
    migrations: manifest.migrations.map((entry) => ({
      name: entry.name,
      files: Object.fromEntries(Object.entries(entry.files).sort(([a], [b]) => a.localeCompare(b))),
    })),
    retired: manifest.retired.map((entry) => ({ name: entry.name, checksum: entry.checksum })),
  };
  return `${JSON.stringify(ordered, null, 2)}\n`;
}
